include current-theme.conf

font_family      ProFont IIx Nerd Font Mono 
bold_font        ProFont IIx Nerd Font Mono 
italic_font      ProFont IIx Nerd Font Mono 
bold_italic_font ProFont IIx Nerd Font Mono 


font_size 12.0

#background_opacity 0.90

window_padding_width	10 


