include current-theme.conf

font_family      BigBlueTerm437 Nerd Font 
bold_font        BigBlueTerm437 Nerd Font 
italic_font      BigBlueTerm437 Nerd Font 
bold_italic_font BigBlueTerm437 Nerd Font 


font_size 16.0
modify_font cell_height 5px

background_opacity 0.90

window_padding_width	10 


